// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "kzankpe",
            "url": "https://github.com/kzankpe"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exercises": {
            "put": {
                "tags": [
                    "Exercises"
                ],
                "responses": {}
            },
            "post": {
                "tags": [
                    "Exercises"
                ],
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Exercises"
                ],
                "responses": {}
            }
        },
        "/workouts": {
            "put": {
                "tags": [
                    "Workouts"
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Workouts"
                ],
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Workouts"
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Workout Tracker Service",
	Description:      "A simple Service using RESTful API that allows users to track their workouts",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
